version: "3"
services:
  db:
    image: postgres
    container_name: threesmart-db
    environment:
      POSTGRES_USER: threesmart
      POSTGRES_DB: threesmart
      POSTGRES_PASSWORD: threesmart
    expose:
      - 5433
    ports:
      - "5433:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  backend:
    build: .
    container_name: threesmart-backend
    ports:
      - "7801:7801"