server:
  port: 7801
spring:
  datasource:
    username: threesmart
    password: threesmart
    url: jdbc:postgresql://host.docker.internal:5433/threesmart
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: validate
