server:
  port: 7802
  error:
    include-message: always
spring:
  datasource:
    username: threesmart
    url: jdbc:postgresql://localhost:5434/threesmart
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: validate
    password: threesmart
    web:
      resources:
        add-mappings: true